# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "771263eab41b997e2f158c98a9dd728b"
name = "Loom - Offer & Sales"
application_url = "https://adloom-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
uri = "/webhooks"
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[[webhooks.subscriptions]]
uri = "/webhooks"
topics = [ "app/uninstalled" ]

[[webhooks.subscriptions]]
uri = "/webhooks/app/subscription_update"
topics = [ "app_subscriptions/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://adloom-production.up.railway.app/auth/callback",
  "https://adloom-production.up.railway.app/auth/shopify/callback",
  "https://adloom-production.up.railway.app/api/auth/callback"
]

[app_proxy]
url = "https://adloom-production.up.railway.app/app/proxy"
prefix = "apps"
subpath = "timer"

[build]
automatically_update_urls_on_dev = true
